### ISSUE TITLE
Prefer CMake's automatic export define

### ISSUE THREAD

**Issue by robertmaynard** [jgcoded/CMakeStarter#9]
Hi,

When scanning the default scaffold code  I see the following code block
```cmake
set(COMPILE_DEFINITIONS )
# This if-block sets the appropriate compiler preprocessor macro needed by
# the library code. On windows, this is needed when importing/exporting DLLs.
if(mylib_STATIC)
    set(BUILD_TYPE "STATIC")
    # Add any other static library specific compiler preprocessor flags here.
    set(COMPILE_DEFINITIONS mylib_STATIC)
else()
    set(BUILD_TYPE "SHARED")
    # Add any other shared library specific compiler preprocessor flags here. 
    set(COMPILE_DEFINITIONS mylib_EXPORT)
endif()
```

This can be entirely removed since when building as a shared library CMake will automatically provide the define ```mylib_EXPORTS``` ( Controlled by the DEFINE_SYMBOL target property ).

**Comment by jgcoded** [comment]
Good catch. I had no idea this existed in CMake

**Comment by chuckatkins** [comment]
Similarly, rather than have the separate mylib_STATIC option, cmake has a built in `BUILD_SHARED_LIBS` option that can be set to `ON` or `OFF`.

**Comment by jgcoded** [comment]
I've updated the CMake code to use the ```BUILD_SHARED_LIBS``` and ```<target>_EXPORTS``` in 3cd280771b424178cea1a8e35690e3023ec2c726
